SUPPORTED_DEVICE_MODELS = [
    {
        "manufacturer": "Kyocera",
        "device_family": "Kyocera E4610",
        "model_name": "E4610",
        "model_aliases": "DuraXV LTE,E4610",
        "repair_policy": "repair_first",
        "notes": "Support battery, cleaning, keypad/buttons, housing/back cover, speaker/earpiece if non-soldering. Charging repair quote only.",
    },
    {
        "manufacturer": "Kyocera",
        "device_family": "Kyocera Cadence",
        "model_name": "S2720",
        "model_aliases": "Cadence,S2720",
        "repair_policy": "repair_if_simple",
        "notes": "Charging port repairs requiring soldering are excluded for now.",
    },
    {
        "manufacturer": "Kyocera",
        "device_family": "Kyocera DuraXV Extreme",
        "model_name": "E4810/E4811",
        "model_aliases": "E4810,E4811,DuraXV Extreme",
        "repair_policy": "repair_first",
        "notes": "Main supported rugged flip category. Verify exact parts compatibility.",
    },
    {
        "manufacturer": "Kyocera",
        "device_family": "Kyocera DuraXV Extreme+/Epic/Equip family",
        "model_name": "E4830/E4831",
        "model_aliases": "E4830,E4831",
        "repair_policy": "repair_first",
        "notes": "Verify exact model and carrier variant before parts order.",
    },
    {
        "manufacturer": "LG",
        "device_family": "LG Classic",
        "model_name": "LG Classic",
        "model_aliases": "L125DL,Classic Flip",
        "repair_policy": "repair_if_simple",
        "notes": "Good candidate for battery/LCD/housing if cost-effective.",
    },
    {
        "manufacturer": "LG",
        "device_family": "LG Exalt",
        "model_name": "LG Exalt",
        "model_aliases": "VN220,Exalt LTE",
        "repair_policy": "repair_if_simple",
        "notes": "Repair if customer values device; otherwise replacement may be better.",
    },
    {
        "manufacturer": "FIG",
        "device_family": "FIG",
        "model_name": "FIG",
        "model_aliases": "Fig Flip,Fig",
        "repair_policy": "quote_only",
        "notes": "Battery/setup focus. Shell/housing can be expensive.",
    },
    {
        "manufacturer": "FIG",
        "device_family": "FIG Mini",
        "model_name": "FIG Mini",
        "model_aliases": "Fig Mini,Fig Mini II",
        "repair_policy": "quote_only",
        "notes": "Battery/setup focus. Track real demand.",
    },
    {
        "manufacturer": "Wonder",
        "device_family": "Wonder",
        "model_name": "Wonder",
        "model_aliases": "Wonder Phone",
        "repair_policy": "quote_only",
        "notes": "Support only after demand and parts availability are proven.",
    },
    {
        "manufacturer": "CAT",
        "device_family": "CAT S22",
        "model_name": "CAT S22 Flip",
        "model_aliases": "CAT S22,S22 Flip",
        "repair_policy": "quote_only",
        "notes": "Smart-flip category. Support setup and some hardware quote-only.",
    },
    {
        "manufacturer": "Qin",
        "device_family": "Qin",
        "model_name": "Qin",
        "model_aliases": "Qin F21,Qin F22,Qin F21 Pro,Qin F22 Pro",
        "repair_policy": "support_setup_only",
        "notes": "Setup/support first; hardware quote-only.",
    },
]


REPAIR_CATEGORIES = [
    {
        "name": "Battery Replacement",
        "description": "Replace removable or serviceable battery.",
        "default_policy": "standard",
        "requires_soldering": 0,
    },
    {
        "name": "Charging Port Cleaning",
        "description": "Inspect and clean charging path without solder work.",
        "default_policy": "standard",
        "requires_soldering": 0,
    },
    {
        "name": "Charging Port Replacement",
        "description": "Replace charging port when supported by current capability.",
        "default_policy": "quote_only",
        "requires_soldering": 1,
    },
    {
        "name": "Screen/LCD Replacement",
        "description": "Replace supported inner or outer display components.",
        "default_policy": "standard",
        "requires_soldering": 0,
    },
    {
        "name": "Hinge/Housing Repair",
        "description": "Repair or replace non-soldering housing parts.",
        "default_policy": "quote_only",
        "requires_soldering": 0,
    },
    {
        "name": "Keypad/Button Repair",
        "description": "Service keypad and button issues where parts are available.",
        "default_policy": "standard",
        "requires_soldering": 0,
    },
    {
        "name": "Speaker/Earpiece Repair",
        "description": "Repair speaker or earpiece when no soldering is required.",
        "default_policy": "standard",
        "requires_soldering": 0,
    },
    {
        "name": "Microphone Repair",
        "description": "Microphone repair is quote-only if soldering would be required.",
        "default_policy": "quote_only",
        "requires_soldering": 1,
    },
    {
        "name": "SIM/Contact Transfer",
        "description": "Move SIM and basic contact data where supported.",
        "default_policy": "standard",
        "requires_soldering": 0,
    },
    {
        "name": "Filter/Setup Support",
        "description": "Support kosher filter and setup tasks.",
        "default_policy": "standard",
        "requires_soldering": 0,
    },
    {
        "name": "Water Damage Diagnostic",
        "description": "Diagnostic-only handling for water-damaged devices.",
        "default_policy": "diagnostic_only",
        "requires_soldering": 0,
    },
]